# `pexl` model and semantic API

This notebook is a living reference for the Python-side PEExcel model.

It documents the **current public model**.

Current conceptual model:

```text
PEExcel workbook / export file
        |
        v
     Project
        |
        +-- Scenario   (one Excel scenario/variant column)
        +-- Scenario
        +-- Scenario
```

A `Scenario` has three different naming concepts:

- `scenario.column_name` — "Scenario" or "Variant", exact Excel scenario-column header; unique inside the `Project`
- `scenario.project_name` — "District" or "Project" context of the scenario, convenience access to `scenario.v.project_name`
- `scenario.name` — "Scenario / Variant" convenience access to `scenario.v.project_scenario_name`; **not necessarily unique**

There is deliberately **no `District` domain object**. District/project grouping is ordinary scenario data (`project_name`).

## 0. Imports and autoreload

During library development, autoreload makes it possible to edit `pexl` modules and rerun notebook cells without restarting the kernel.

In [376]:
%load_ext autoreload
%autoreload 2

from pathlib import Path
import pandas as pd

from pexl import Project

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## 1. Read a PEExcel project workbook

`Project.from_excel(...)` reads the PEExcel Project File `IN` / `OUT` sheet scenario columns into one `Project` containing an ordered set of `Scenario` objects.

The exact Excel scenario column name is kept as structural identity. `project_name` and `project_scenario_name` are loaded like all other schema variables.

In [377]:
PROJECT_PATH = Path("../data/exports/ka_project_backup_v1_12.xlsx")

project = Project.from_excel(PROJECT_PATH)
project

### Project overview

The project is both iterable and indexable by scenario position or exact scenario column name.

In [378]:
print(project)
print("Scenario count:", len(project))
print("Warning count:", len(project.warnings))
print("Projects/Districts:", len(project.project_names()))
print("Project/group names:", project.project_names())

<Project scenarios=42 warnings=18 source='..\\data\\exports\\ka_project_backup_v1_12.xlsx'>
Scenario count: 42
Warning count: 18
Projects/Districts: 17
Project/group names: ['Neues Projekt', 'Forsthausgasse', 'Campo Breitenlee', 'EFHk', 'MFHo', 'MFHk', 'GWBk', 'GWBg', 'DLG1k', 'DLG1g', 'DLG2k', 'DLG2g', 'DLG3k', 'DLG3g', 'GNICE', 'Gründerzeit Beispiel', 'Büro']

In [379]:
project.warnings[:10]

["Column 'Default': conventional project name 'Default' does not match project_name='Neues Projekt'",
 "Column 'Default': conventional scenario name 'Default' does not match project_scenario_name='Basis'",
 "Column 'EFHo | nach 2020': conventional project name 'EFHo' does not match project_name='Forsthausgasse'",
 "Column 'EFHo | nach 2020': conventional scenario name 'nach 2020' does not match project_scenario_name='BT2 DE Südtiroler FLEX1,7xPV'",
 "Column 'DLG1k | Büro - 2010 - 2030': conventional scenario name 'Büro - 2010 - 2030' does not match project_scenario_name='Büro - bis 1978'",
 "Column 'DLG1g | Büro - 2010 - 2030': conventional scenario name 'Büro - 2010 - 2030' does not match project_scenario_name='Büro - bis 1978'",
 "Column 'DLG2k | Büro - 2010 - 2030': conventional scenario name 'Büro - 2010 - 2030' does not match project_scenario_name='Büro - bis 1978'",
 "Column 'DLG2g | Büro - 2010 - 2030': conventional scenario name 'Büro - 2010 - 2030' does not match project_scenario_name='Büro - bis 1978'",
 "Column 'DLG3k | Büro - 2010 - 2030': conventional scenario name 'Büro - 2010 - 2030' does not match project_scenario_name='Büro - bis 1978'",
 "Column 'DLG3g | Büro - 2010 - 2030': conventional scenario name 'Büro - 2010 - 2030' does not match project_scenario_name='Büro - bis 1978'"]

## 2. Scenario identity and direct project access

A `Scenario` corresponds exactly to one scenario/variant column in the workbook.

The **column name** is the unique structural identifier. The semantic names stored inside the scenario are intentionally kept separate.

In [380]:
s0 = project[1]
s0

In [381]:
print("Excel column:", s0.column_name)
print("project_name:", s0.project_name)
print("project_scenario_name:", s0.name)

Excel column: Forsthausgasse | BT2 KON FW
project_name: Forsthausgasse
project_scenario_name: BT2 KON FW

Look up a scenario directly by its exact Excel column header:

In [382]:
example_column = project.column_names()[9]
project[example_column]

Scenario names are not required to be unique, while column names are:

In [383]:
print("Example column names:", *project.column_names()[4:9], sep="\n")
print()
print("Example scenario names:", *project.scenario_names()[4:9], sep="\n")

Example column names:
EFHk | nach 2020
MFHo | nach 2020
MFHk | nach 2020
GWBk | nach 2020
GWBg | nach 2020

Example scenario names:
nach 2020
nach 2020
nach 2020
nach 2020
nach 2020

## 3. Direct variable and metadata access

For known PEExcel variables, the most direct interface is still `scenario.v.<var_name>`.

The generated schema metadata is available in parallel via `scenario.meta.<var_name>`.

In [384]:
print("Project/group:", s0.v.project_name)
print("Scenario:", s0.v.project_scenario_name)
print("Description:", s0.v.project_description)
print("Total GFA:", s0.v.GFA_total)

Project/group: Forsthausgasse
Scenario: BT2 KON FW
Description: VORENTWURF, FORSTHAUSGASSE 9, 1200 WIEN
Total GFA: 6887.56

### ".meta" dotted access to all variable metadata

In [385]:
v = s0.meta.Batt_c_rate
v

In [386]:
for attrib, k in v.__dict__.items():
    print("v.", attrib, " = ", k, sep="")

v.var_name = Batt_c_rate
v.attr_name = Batt_c_rate
v.icon = 🔋
v.label_de = Maximale Be/Entladeleistung
v.unit = ratio
v.comment = None
v.source = IN
v.ka = 2
v.domain = battery
v.measure = c_rate
v.spatial_scope = None
v.temporal_scope = None
v.entity_group = None
v.entity_key = None

In [387]:
vars(s0.meta.GFA_total)

{'var_name': 'GFA_total',
 'attr_name': 'GFA_total',
 'icon': '🏙️',
 'label_de': 'BGF Quartier',
 'unit': 'm²',
 'comment': None,
 'source': 'IN',
 'ka': 0,
 'domain': 'usage',
 'measure': 'area',
 'spatial_scope': 'GFA',
 'temporal_scope': None,
 'entity_group': None,
 'entity_key': None}

The schema metadata is the foundation for generic tooling. Important semantic fields include:

- `source` (`IN`, `OUT`, `BOTH`)
- `ka`
- `domain`
- `measure`
- `spatial_scope`
- `temporal_scope`
- `entity_group`
- `entity_key`
- label, unit, comment, icon

## 4. Selection vs. View

The refactored API separates two concepts deliberately.

### Selection = *which objects?*

- `VariableSelection` is an ordered, read-only collection of selected `VariableMeta` objects.
- `ScenarioSelection` is an ordered, read-only collection of selected `Scenario` objects.

Selections behave like small sequences:

```python
len(selection)
selection[0]
selection[:3]
for item in selection: ...
```

### View = *values at the intersection of selections*

- `ScenarioView` = one `Scenario` × one `VariableSelection`
- `ProjectView` = one `ScenarioSelection` × one `VariableSelection`

Views are datasets rather than collections. Their main responsibilities are filtering and materialization (`shape`, `values`, `to_records`, ...).

## 5. Project views: `view`, `inn`, `out`

`Project` and `Scenario` are the public entry points. Selection classes normally remain infrastructure behind these façades.

For a project:

- `project.view` — all schema variables across all scenarios
- `project.inn` — `IN` + `BOTH` variables across all scenarios
- `project.out` — `OUT` + `BOTH` variables across all scenarios

In [388]:
project.out

In [389]:
x = project.out.select(
    domain="primary_energy_balance",
    measure="demand",
)
x

Inspect the two selected axes directly:

In [390]:
print(x.variables)
print(x.scenarios)

<VariableSelection n=11>
<ScenarioSelection n=42>

In [391]:
print("Selected variable count:", len(x.variables))
print("First variable:", x.variables[0])
print("Variable names:", *x.variables.var_names, sep="\n")

Selected variable count: 11
First variable: <VarMeta PEI_demand [kWhPEges./m²NGFa] @OUT>
Variable names:
PEI_demand
PEI_el_plugloads
PEI_el_hvac
PEI_district_heating
PEI_natural_gas
PEI_biomass
PEI_other
PEI_mob_total
PEI_mob_fossile
PEI_mob_el
PEI_storage_losses

In [392]:
print("Selected scenario count:", len(x.scenarios))
print("First scenario:", x.scenarios[0])
print("First column names:", x.scenarios.column_names[:5])

Selected scenario count: 42
First scenario: <Scenario column='Default' project='Neues Projekt' name='Basis'>
First column names: ['Default', 'Forsthausgasse | BT2 KON FW', 'Campo Breitenlee | Basis', 'EFHo | nach 2020', 'EFHk | nach 2020']

## 6. Filter scenarios independently

`.where(...)` acts on the **scenario axis** and delegates to `ScenarioSelection.where(...)`.

It filters scenarios using ordinary schema-variable values. This is generic; preset filtering is only one use case.

In [393]:
forsthaus = project.view.where(project_name="Forsthausgasse")
forsthaus

In [394]:
for scenario in forsthaus.scenarios:
    print(scenario.column_name)

Forsthausgasse | BT2 KON FW
EFHo | nach 2020
Forsthausgasse | BT2 ÖKO WP FLEX 2,6xPV
Forsthausgasse | BT2 ÖKO ALT WP FLEX 1,7xPV
Forsthausgasse | BT2 ÖKO2 WP FLEX 2,6xPV
Forsthausgasse | BT2 ÖKO3 WP FLEX 2,6xPV
Forsthausgasse | BT2 UTO WP FLEX 1,7xPV
Forsthausgasse | BT2 DE Südtiroler FLEX1,7xPV
Forsthausgasse | BT2 AW Leichtbau FLEX 1,7xPV

Example for preset-driven filtering (only if the workbook actually contains that preset value):

In [395]:
project.project_names()

['Neues Projekt',
 'Forsthausgasse',
 'Campo Breitenlee',
 'EFHk',
 'MFHo',
 'MFHk',
 'GWBk',
 'GWBg',
 'DLG1k',
 'DLG1g',
 'DLG2k',
 'DLG2g',
 'DLG3k',
 'DLG3g',
 'GNICE',
 'Gründerzeit Beispiel',
 'Büro']

In [396]:
presets = project.view.where(project_name="Campo Breitenlee").select(measure="preset")
presets.to_frame()

,preset_recorded_renovation,preset_recorded_geometry,preset_recorded_hulls,preset_recorded_building_mass,preset_recorded_shading_geometry,preset_recorded_mobile_shading,preset_recorded_air_tightness,preset_recorded_vent_modes,preset_recorded_vent_night_modes,preset_recorded_ventilation_system,...,preset_recorded_heating_system,preset_recorded_cooling_period,preset_recorded_cooling_modes,preset_recorded_cooling_system,preset_recorded_dhw_system,preset_recorded_flexibility_system,preset_recorded_flexibility_thermal,preset_recorded_battery_system,preset_recorded_mobility,preset_recorded_construction_type
column_name,,,,,,,,,,,,,,,,,,,,,
Campo Breitenlee | Basis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [397]:
# Inspect available values first rather than hard-coding one.
preset_var = "preset_recorded_heating_system"

if hasattr(project[0].v, preset_var):
    print(project.view.scenarios.unique(preset_var)[:20])

[nan]

### Variable and scenario filters are orthogonal

The order of `.select(...)` and `.where(...)` must not affect the result.

In [398]:
a = (
    project.out
    .select(domain="primary_energy_balance")
    .where(project_name="Forsthausgasse")
)

b = (
    project.out
    .where(project_name="Forsthausgasse")
    .select(domain="primary_energy_balance")
)

print(a.shape, b.shape)
print(a.to_records() == b.to_records())

(9, 20) (9, 20)
True

## 7. Materialize a `ProjectView`

`ProjectView` represents a two-dimensional dataset:

```text
scenarios × variables
```

`column_name` is used as the unique scenario identifier in record-oriented outputs.

In [399]:
records = x.to_records()
records[:2]

[{'column_name': 'Default',
  'PEI_demand': 99.13914501616482,
  'PEI_el_plugloads': 39.785566227928854,
  'PEI_el_hvac': 9.47998136046069,
  'PEI_district_heating': 0,
  'PEI_natural_gas': 49.87359742777527,
  'PEI_biomass': 0,
  'PEI_other': 0,
  'PEI_mob_total': 27.02064638262062,
  'PEI_mob_fossile': 14.817841726618706,
  'PEI_mob_el': 12.202804656001913,
  'PEI_storage_losses': 0},
 {'column_name': 'Forsthausgasse | BT2 KON FW',
  'PEI_demand': 65.18411040947784,
  'PEI_el_plugloads': 39.785566227928854,
  'PEI_el_hvac': 4.968117797539386,
  'PEI_district_heating': 20.430426384009603,
  'PEI_natural_gas': 0,
  'PEI_biomass': 0,
  'PEI_other': 0,
  'PEI_mob_total': 17.608640532251034,
  'PEI_mob_fossile': 9.656395510791368,
  'PEI_mob_el': 7.952245021459666,
  'PEI_storage_losses': 0}]

In [400]:
df = pd.DataFrame(records).set_index("column_name")
df.head()

,PEI_demand,PEI_el_plugloads,PEI_el_hvac,PEI_district_heating,PEI_natural_gas,PEI_biomass,PEI_other,PEI_mob_total,PEI_mob_fossile,PEI_mob_el,PEI_storage_losses
column_name,,,,,,,,,,,
Default,99.139145,39.785566,9.479981,0.000000,49.873597,0.0,0.0,27.020646,14.817842,12.202805,0.0
Forsthausgasse | BT2 KON FW,65.184110,39.785566,4.968118,20.430426,0.000000,0.0,0.0,17.608641,9.656396,7.952245,0.0
Campo Breitenlee | Basis,76.127065,41.415332,34.711732,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0
EFHo | nach 2020,78.308000,39.785566,17.005791,21.516643,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0
EFHk | nach 2020,112.048770,39.785566,10.408002,0.000000,61.855202,0.0,0.0,0.000000,0.000000,0.000000,0.0

This is already sufficient for many comparison and dashboard tasks. A dedicated `ProjectView.to_frame()` convenience method is a likely next extension; see the future API section below.

## 8. Scenario views

A `ScenarioView` is intentionally only a shallow one-scenario specialization of the same view concept.

- `scenario.view` — all variables
- `scenario.inn` — input variables
- `scenario.out` — output variables

Only the variable axis is selectable because the scenario axis is already fixed.

In [401]:
s0.out

In [402]:
pe0 = s0.out.select(domain="primary_energy_balance")
pe0

In [403]:
pe0.to_var_dict()

{'context_factor_density': 39.960583066314804,
 'context_factor_mobility': 14.107740396658576,
 'context_factor_renovation': 0,
 'PEI_demand': 65.18411040947784,
 'PEI_el_plugloads': 39.785566227928854,
 'PEI_el_hvac': 4.968117797539386,
 'PEI_district_heating': 20.430426384009603,
 'PEI_natural_gas': 0,
 'PEI_biomass': 0,
 'PEI_other': 0,
 'PEI_mob_total': 17.608640532251034,
 'PEI_mob_fossile': 9.656395510791368,
 'PEI_mob_el': 7.952245021459666,
 'PEI_storage_losses': 0,
 'PEI_cf_density': 39.960583066314804,
 'PEI_cf_mobility': 14.107740396658576,
 'PEI_cf_renovation': 0,
 'PEI_sub_PV': 4.364628034660361,
 'PEI_sub_flex': 0,
 'PEI_balance': -24.359799444095128}

Direct selected-variable access remains convenient when the variable is known:

In [404]:
# Only succeeds if QH is part of the selected view.
heat = s0.out.select(domain="heat_balance")
print("QH:", heat.QH)

QH: 31.824263823108204

## 9. Explore the semantic schema through selections

Semantic introspection belongs to `VariableSelection`, not to the View itself.

In [405]:
print("OUT domains:")
print(s0.out.domains())

OUT domains:
['weather', 'useful_energy', 'heat_balance', 'comfort', 'electricity_end_use', 'electricity_dispatch', 'energy_dispatch', 'final_energy', 'primary_energy_balance', 'pe_import_export_balance', 'embodied_emissions', 'operational_emissions', 'mobility', 'dhw', 'heating', 'cooling']

In [406]:
print("IN entity groups:")
print(s0.inn.entity_groups())

IN entity groups:
['mobility', 'usage', 'hull', 'heating', 'cooling', 'dhw', 'component', 'energy_carrier']

In [407]:
usage_residential = s0.inn.select(
    entity_group="usage",
    entity_key="residential",
)
usage_residential

In [425]:
heating_inputs = s0.inn.select(
    entity_group="heating",
    source="IN"
)
heating_inputs

This pattern is intended for generic processing such as:

- selecting related inputs/outputs without hard-coded lists
- building scenario-comparison tables
- generating filter controls from metadata
- feeding reporting/diagram specifications
- validating schema coverage

## 10. Compare scenarios through a `ProjectView`

Manual pairwise dictionary comparison remains possible, but the preferred model is to select the relevant variables and scenarios first, then materialize the resulting project view.

In [435]:
comparison = (
    project.view.select(
    domain="energy_dispatch",
    source="OUT"
    )
)

comparison.to_frame()

,EUIh_district_heating,EUIdhw_district_heating,EUI_district_heating,EUIh_natural_gas,EUIdhw_natural_gas,EUI_natural_gas,EUIh_biomass,EUIdhw_biomass,EUI_biomass,EUIh_other,EUIc_other,EUIdhw_other,EUI_other,EUI_mob_fossil,EUIh_2th,EUIh_4th,EUIc_2th,EUIdhw_1th,EUIdhw_2th
column_name,,,,,,,,,,,,,,,,,,,
Default,0.000000,0.000000,0.000000,31.071879,14.267755,45.339634,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.348201,31.071879,0.0,0.0,14.267755,0.0
Forsthausgasse | BT2 KON FW,35.174186,14.954144,50.128330,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.046996,35.174186,0.0,0.0,14.954144,0.0
Campo Breitenlee | Basis,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0
EFHo | nach 2020,65.201949,0.000000,65.201949,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,65.201949,0.0,0.0,0.000000,0.0
EFHk | nach 2020,0.000000,0.000000,0.000000,38.414247,17.817755,56.232001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,38.414247,0.0,0.0,17.817755,0.0
MFHo | nach 2020,0.000000,0.000000,0.000000,38.893213,17.817755,56.710967,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,38.893213,0.0,0.0,17.817755,0.0
MFHk | nach 2020,0.000000,0.000000,0.000000,35.276416,17.817755,53.094171,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,35.276416,0.0,0.0,17.817755,0.0
GWBk | nach 2020,0.000000,0.000000,0.000000,33.130442,17.817755,50.948196,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,33.130442,0.0,0.0,17.817755,0.0
GWBg | nach 2020,0.000000,0.000000,0.000000,29.710304,17.817755,47.528059,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,29.710304,0.0,0.0,17.817755,0.0
DLG1k | Büro - 2010 - 2030,0.000000,0.000000,0.000000,0.000000,3.773842,3.773842,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,3.773842,0.0
DLG1g | Büro - 2010 - 2030,0.000000,0.000000,0.000000,0.000000,3.773842,3.773842,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,3.773842,0.0
DLG2k | Büro - 2010 - 2030,0.000000,0.000000,0.000000,0.000000,3.773842,3.773842,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,3.773842,0.0
DLG2g | Büro - 2010 - 2030,0.000000,0.000000,0.000000,0.000000,3.773842,3.773842,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,3.773842,0.0
DLG3k | Büro - 2010 - 2030,0.000000,0.000000,0.000000,0.000000,3.773842,3.773842,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,3.773842,0.0
DLG3g | Büro - 2010 - 2030,0.000000,0.000000,0.000000,0.000000,3.773842,3.773842,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,3.773842,0.0
DLG1k | Bildung - 2010 - 2030,0.000000,0.000000,0.000000,0.000000,6.398639,6.398639,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,6.398639,0.0
DLG1g | Bildung - 2010 - 2030,0.000000,0.000000,0.000000,0.000000,6.398639,6.398639,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,6.398639,0.0
DLG2k | Bildung - 2010 - 2030,0.000000,0.000000,0.000000,0.000000,6.398639,6.398639,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,6.398639,0.0
DLG2g | Bildung - 2010 - 2030,0.000000,0.000000,0.000000,0.000000,6.398639,6.398639,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,6.398639,0.0
DLG3k | Bildung - 2010 - 2030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DLG3g | Bildung - 2010 - 2030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DLG1k | Handel - 2010 - 2030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DLG1g | Handel - 2010 - 2030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DLG2k | Handel - 2010 - 2030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DLG2g | Handel - 2010 - 2030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DLG3k | Handel - 2010 - 2030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DLG3g | Handel - 2010 - 2030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GNICE | Quick-Check,0.000000,0.000000,0.000000,224.475713,14.948312,239.424024,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,224.475713,0.0,0.0,14.948312,0.0
GNICE | QC Flexibel,0.000000,0.000000,0.000000,224.475713,14.948312,239.424024,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,224.475713,0.0,0.0,14.948312,0.0
GNICE | Quick-Check_2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0
"GNICE | QC Flex GFZ 2,2",0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0
"Forsthausgasse | BT2 ÖKO WP FLEX 2,6xPV",24.045607,0.000000,24.045607,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.046996,24.045607,0.0,0.0,0.000000,0.0
"Forsthausgasse | BT2 ÖKO ALT WP FLEX 1,7xPV",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Forsthausgasse | BT2 ÖKO2 WP FLEX 2,6xPV",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Forsthausgasse | BT2 ÖKO3 WP FLEX 2,6xPV",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Forsthausgasse | BT2 UTO WP FLEX 1,7xPV",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Forsthausgasse | BT2 DE Südtiroler FLEX1,7xPV",24.045607,0.000000,24.045607,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.046996,24.045607,0.0,0.0,0.000000,0.0
"Forsthausgasse | BT2 AW Leichtbau FLEX 1,7xPV",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GNICE | Sanierung Zellulose,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0
Gründerzeit Beispiel | Bestand,0.000000,0.000000,0.000000,192.461092,14.954144,207.415236,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,192.461092,0.0,0.0,14.954144,0.0
Gründerzeit Beispiel | Saniert mit GWWP,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0
Büro | preset test,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0

For a narrow pairwise comparison, structural scenario identity should be used rather than non-unique `scenario.name` values.

In [436]:
if len(comparison.scenarios) >= 2:
    left = comparison.scenarios[0]
    right = comparison.scenarios[1]

    left_values = left.inn.select(domain="usage").to_var_dict()
    right_values = right.inn.select(domain="usage").to_var_dict()

    differences = {
        var_name: (left_values[var_name], right_values[var_name])
        for var_name in left_values
        if left_values[var_name] != right_values[var_name]
    }

    list(differences.items())[:20]

## 11. Modify scenario data

Scenario values remain directly writable through `scenario.v`.

The semantic views are read-only façades over those values.

In [437]:
scenario_edit = project[1]

print("Scenario:", scenario_edit.column_name)
print("Before:", scenario_edit.v.GFA_office)

Scenario: Forsthausgasse | BT2 KON FW
Before: 0

In [411]:
# Example mutation — uncomment if desired.
# scenario_edit.v.GFA_office = 250.0
# print("After:", scenario_edit.v.GFA_office)

Potential future convenience APIs worth discussing here include validation-aware setters, immutable/copy-on-write scenarios, and batch assignment through selections. None of these are part of the current model yet.

## 12. Create a new project and scenario

A `Project` can also be built in Python without an existing workbook.

A new `Scenario` needs a unique structural `column_name`. Its semantic names remain normal schema values.

In [438]:
from pexl.model.scenario import Scenario

new_project = Project()
new_scenario = Scenario("Example Project | Variant A")

new_scenario.v.project_name = "Example Project"
new_scenario.v.project_scenario_name = "Variant A"
new_scenario.v.GFA_office = 250.0

new_project.add_scenario(new_scenario)
new_project

In [439]:
new_project["Example Project | Variant A"]

### Copying an existing scenario

There is no dedicated public `Scenario.copy(...)` API yet. If scenario cloning becomes common, it should be added explicitly rather than duplicated ad hoc in client code.

A future API might look like:

```python
variant = source.copy(
    column_name="Example Project | Variant B",
    project_name="Example Project",
    name="Variant B",
)
```

This is a **design sketch**, not current API.

## 13. Export

The current Python writer serializes project scenario data back to an Excel-style `IN` sheet and can add a `META` sheet.

Important invariant: export uses `Scenario.column_name` directly. It does **not** reconstruct the column header from `project_name` + `project_scenario_name`.

In [414]:
# Example:
# new_project.to_excel("../data/exports/new_project.xlsx")

The import layer may warn when the conventional column name (`project_name | project_scenario_name`) does not match the values stored inside the scenario, but the actual Excel column header remains authoritative structural identity.

# Future API and reporting/diagram discussion

The sections below are intentionally **design sketches**, not executable current API. They document likely extensions needed for Streamlit dashboards, scenario comparison and PEExcel reporting.

## 14. DataFrame materialization

The current bridge is:

```python
pd.DataFrame(view.to_records()).set_index("column_name")
```

A natural convenience extension would be:

```python
view.to_frame()       # wide: scenarios × variables
view.to_long_frame()  # tidy: scenario × variable × value + metadata
```

Possible long-form columns:

```text
column_name
project_name
project_scenario_name
var_name
label_de
unit
domain
measure
entity_group
entity_key
value
```

### Open questions

- Should pandas be a core dependency of `pexl`, an optional dependency, or confined to an adapter module?
- Should `to_frame()` expose canonical `var_name`, Python `attr_name`, or configurable columns?
- Should metadata be returned as extra columns or via a separate metadata frame?

## 15. Scenario-selection ergonomics

Current conceptual API:

```python
project.out.where(project_name="Forsthausgasse")
project.out.where(preset_recorded_heating_system="...")
```

`ScenarioSelection` should remain generic: presets are ordinary scenario variables, not special selection concepts.

Likely useful additions to discuss:

```python
selection.unique("preset_recorded_heating_system")
selection.column_names
selection.names
selection.project_names
```

Potential later predicates:

```python
selection.where_in(project_name=[...])
selection.where_not(...)
selection.filter(callable)
```

These should only be added when concrete use cases require them; avoid turning `ScenarioSelection` into a dataframe query language prematurely.

## 16. Reporting and diagram configuration

The Streamlit prototype currently performs substantial semantic interpretation itself. The target boundary should be:

```text
PEExcel schema + reporting configuration
            |
            v
          pexl
  semantic selection
  scenario comparison
  reporting materialization
            |
            v
   Streamlit / Plotly
   UI + rendering only
```

The existing generated `VariableMeta` already contains intrinsic semantics such as labels, units, domain, measure and entity grouping. These should **not** be duplicated in a chart configuration.

Chart-specific information is presentation metadata and should remain separate from intrinsic variable semantics.

### Proposed workbook-backed reporting configuration

Instead of a separate `chart_info.xlsx`, the human-maintained source could move into technical tables/sheets inside the PEExcel workbook, for example:

```text
REPORT_CHARTS
REPORT_SERIES
REPORT_BANDS
```

The schema/export pipeline can then version and extract these tables together with `IN` and `OUT`.

#### `REPORT_CHARTS`

| chart_id | title_de | chart_type | tab_name | order |
|---|---|---|---|---:|
| primary_energy_balance | Primärenergiebilanz | balance_stack | Primärenergie | 10 |
| heat_balance | Wärmebilanz | balance_stack | Wärmebilanz | 20 |

#### `REPORT_SERIES`

| chart_id | series_id | source_var | role | transform | color | pattern | order |
|---|---|---|---|---|---|---|---:|
| primary_energy_balance | plugloads | PEI_el_plugloads | Bedarf | identity | #7e1141 | | 10 |
| primary_energy_balance | density_neg | PEI_cf_density | Bedarf | negative_part | #F281BB | / | 90 |
| primary_energy_balance | density_pos | PEI_cf_density | Deckung | positive_part | #F281BB | / | 100 |

The distinction `series_id != var_name` is important because one variable may generate multiple presentation series.

## 17. Derived reporting series

Diagram-only series such as positive/negative parts of a signed context factor should **not** become fake PEExcel `OUT` variables.

A small controlled transform vocabulary could cover the first reporting needs:

```text
identity
abs
positive_part
negative_part
negate
```

Avoid arbitrary Python expressions in reporting configuration.

Example concept:

```text
source_var = PEI_cf_density
transform  = positive_part
role       = Deckung
```

## 18. Renderer-neutral reporting layer

A later `pexl.reporting` package could translate reporting specifications + `ProjectView` into chart-ready data, while remaining independent of Plotly or Streamlit.

Possible domain objects:

```text
ReportSpec
ChartSpec
SeriesSpec
BandSpec
```

Possible usage sketch:

```python
# FUTURE API — not implemented
chart = report["primary_energy_balance"]
chart_data = chart.materialize(project_view)
```

A useful materialized long-form result might look like:

| column_name | series_id | source_var | role | label | value | unit | color | pattern |
|---|---|---|---|---|---:|---|---|---|
| ... | plugloads | PEI_el_plugloads | Bedarf | Nutzerstrom | ... | ... | #7e1141 | |

Streamlit/Plotly would then only render this already-interpreted dataset.

## 19. Intrinsic schema metadata vs. reporting metadata

Recommended boundary:

### Intrinsic → `VariableMeta` / PEExcel schema

- `var_name`
- `label_de`
- `unit`
- `domain`
- `measure`
- `source`
- `ka`
- `spatial_scope`
- `temporal_scope`
- `entity_group`
- `entity_key`
- potentially explicit `dtype`

### Presentation/reporting configuration

- `chart_id`
- `series_id`
- chart membership
- role / stack / destination
- display order
- color
- pattern
- chart-specific label override
- transform
- chart type
- title / tab name
- threshold/reference bands

This avoids two competing sources of truth for semantic metadata.

## 20. Proposed next model extensions

The current model is now sufficient to revisit the Streamlit prototype without immediately adding chart-specific logic to core classes.

Suggested sequence for further discussion:

1. **Stabilize selections and views**
   - sequence ergonomics for both selections
   - scenario column identity tests

2. **Add generic materialization conveniences**
   - `ProjectView.to_frame()`
   - possibly `to_long_frame()`
   - decide pandas dependency boundary

3. **Use the Streamlit prototype against the new model**
   - replace raw `pd.read_excel()` data shaping
   - replace hard-coded preset discovery with schema selection (`measure="preset"`)
   - identify remaining genuinely generic gaps

4. **Design reporting configuration**
   - migrate or normalize `chart_info`
   - separate intrinsic metadata from presentation metadata
   - define controlled transforms

5. **Add renderer-neutral `pexl.reporting` only after the above is stable**

The notebook should be updated alongside these decisions so that it remains an executable description of the intended public API.